sudo: required

language: ruby

services:
  - docker

install:
  - bundle install
  - rake -f ci/Rakefile ci:pull

script: rake -f ci/Rakefile ci:run

matrix:
  include:
    - name: "Ruby 2.5.3 with MXNet 1.3.1 on Python 3.7.2"
      env:
        - ruby_version=2.5.3
        - python_version=3.7.2
        - mxnet_version=1.3.1

    - name: "Ruby 2.4.5 with MXNet 1.3.1 on Python 3.7.2"
      env:
        - ruby_version=2.4.5
        - python_version=3.7.2
        - mxnet_version=1.3.1

    - name: "Ruby 2.3.8 with MXNet 1.3.1 on Python 3.7.2"
      env:
        - ruby_version=2.3.8
        - python_version=3.7.2
        - mxnet_version=1.3.1

  allow_failures:
    - name: "Ruby 2.3.8 with MXNet 1.3.1 on Python 3.7.2"
